branches:
  only:
  - master
language: go
install:
- go get -v github.com/spf13/hugo
- sudo pip install s3cmd
script:
- hugo
deploy:
  provider: s3
  access_key_id: 
  secret_access_key: 
  bucket: kumasan.space
  skip_cleanup: true
  acl: public_read
notifications:
  email: 
  on_failure: always
env:
  global:
  - secure: X72F/IH2jmT+wiOrQahnmlGS3DR7l4i9zPkIlpnIihievwB/UqGpSQZ7ztCcTYrCD5hUu28oS/ZSZH9ZIxH4AvO4+XDrauXLxThcqp0n3DFV6zu4eRpg6kMe4DdBg8kFHNo7vAs65EVQEOCI0BFbPiK2rSEOuDdbAPd4JZgo4ZrvVhmWZ3QX0ldRdCFkidK1tBBcGmNochVYGCTgkGcF7/aX1tN523UF6KF0P8TUvuUVPkqTLMPvh+aQdvbAiMZMUliMFGbyz5BRlBR9yp3uwuC6SbXKIqcIym6DNDCZolJF+tp7V3AL4oXFQV56maW7GyCS+5Xo0r33Y7zFYtpotBTSftwvsM4eLHxE1si2PTolTr5fOmjfxW5qhmUcHF3psQupNb7jKunDTGAf/9B1uAJeEuFt27crUVehjhXerL8m+GNOkpQSPaC+3E9XBM6Z0u6oFjdzL52EBAYIk8gltwWRC/JVB2ZFKs1OmmX8KyUCcvLM7YeHeoY0k6Ta8tCrJ0ivGBjVKlIS0HrgNpm/GPx0aRiO5kOEYDnT43utJ/+xUeym3mSyQXHi7JTaDlwA6bygp2yUoWz+8H6EJwPtbk0RiTF8jQYApA8MgTFMOdbBj78bobooXk+OFQYP/UHtVBvolcs886FyFxd3zWpyWGwWaDaEJV1mYb0A5Z1pRMY=
  - secure: g5p+nC1QgKnbJJqKRHX+bcJZXgPf80CKc+beRJ2ljfU2rgoDumkCr5Pzpdrp2GtvlOL6pSZ0Wm+y4qM/iV064FZjKIIyWK4zwBjD2duf20sxKR2FT7ChRijzuKpbULniCHMywWUi+kkv+QvTaG60e6uBCUf+C4dS1MMv0pYzO9pW4eLfl1oN6wzmZ3SPbbcIVkVGZz4Z8LcZbr1oIc7oleChLZkrRBJbZhB/5YX2Y5GVwFbbiebqWzL286mqHJWXwKmnnVhgPbFfBHYRhE6GWhUQeDT8wj0Eel5cnigHRlx3PVdIGPqJBr23hiGKr2R4RqSUwaUXu/rm16BSHpMvSFdMZRgaLpmxK+zKKG49rxfOgfUhgHZBWM1x0F0hQGdIHN1aDqzK4t4XevFMEHyjTrgZ1h1JkUAB4bN06KFug7+pbBm2giSMxUif69azf0zj/x/YXPRvRfs1M+rZk8p6kQfUtgjxfJerPdN5k27ZhWK4E3+Unh9iMlg8Shpxc028sdfYPBFiSFyw8aBUbRMoilkh19MuGkqAFa9LRIkX8ouFO504zw6++F4r0ggsJ8k6Nc2y3d1qpiu6jM+pIuxxtxJLjWGMGK1e4U6wtu1JEJymrxV6P8UIItMzmKf7Mtdh5HUWExDgEjOGoX94/Ra4C7e7mS1Ahl8geABD2z9HhLE=
