language: go
install:
- go get -v github.com/spf13/hugo
- pip install urllib3[secure] --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: inGtQaI0O6hJH3JXJI2UC2fWE9vDqthyrqBoW8X2u9Vtg3pm0fZ5qfs8wKJI0yUWga6sqHwXORkJBCKwNWYPBinbBCapI96XRuS1Y+2lkHe3uWrOa2DTKoCZ9NVw1WWsrFSRX6VL5N98kP2ruse9hrOKzckhslo/uHUz21pA77OhvEOTw+Yq/g8MKD1uaKDPuRvOf15uxr+XUfhKML8/8948/jkEbUENXl4k+9xzzIOlFum5IMk6UJ1knUuIRF9ZaZ4MxzVgXlO+XJ9ntCW2v7IPmkfMAiUa5JQfpF3hAzGITqfmSoSZCaKPMv/eKQC9N7OhOhsH7+Ikw1+2lfjQknYIuwNvP/qBkBII4iopuw8HQDqXPjDLrAVJIn8DF5+GBjdQHwEuIcaTc68skpkBwstuWZF2uh4qxo/y9zpPu3Xoq8B+CHWEreikUIpvlOLgIvZiF4WAmiMZOi+uA87vW1uAcVlG/drB1mb++giX+DP4HhnJ+bonjqF92gB7ApOr3E1DIk02Sl2E60zOponJIRqdbjp2rhCeoaBsHtk296gT3+k76/+I9PfVjoAqrzxiPGeeRhbKVoNtLeVuM9YnqwnusRXLTcLjtUPP4gYUb84GmM/0HB1HQQ8KtCRhlfzBTn1shqCb637j+bRsU0SRwSrBtlVCWz9b4lEtt6XaGig=
  - secure: kk+rQY4kod3My1C81JoGuKKwJxzpvkhfRHbBkMOm3a1teTV69NtaKvB5BtLa0nUd7DK6ymgfwrBAEufSMAxIGL1s62DYhXA/I3dZxZAQvTiIpjKtqdPbuz563Mu0Q5nKDsh+D4qh0qbyjmVvgCONFH+2GrgH9tSEW/YHLTP2vemNFDjw7keiLnpYXRze9ne398kD9bPGM6aVImwWsaa+VxdFJBVDe/7aCOiFELK7B1umGvnk75CFdE/58NMkLIO3lEyVX8bs2dbfTStTc/lJm/tz5DzqhiGyNhUPgx2LXM2miV3T0KWYl6qPmTuSJrZhLxomlH8dWEYAWQ/jQQIJP7s42GGJzBClVb372OteS+WDARbNKHECNJtI2PaBgO9NbhcBNsgBt4bq8acY2MxWLF+7YkP9u46KGpnj2lkEVgtUIaayDVRI3nH8VhjZH9lQvfAbvuwDu1mSzhsJDY21xgth3bWYLaxOYdtoCPtY/emKh/hIZT0tANZX9buDb8Tv6aIT0IZMx7gaRZ3/XVHRDhXQdOwW+ZUsHDImjmHBbftr/fX8i32qiNyI7YFM7W285NKEC20sG8JSj0HwCin7p+/tetKMjdzm5deWunWYLhuk+N9rfFuyYZmBH4dZ4LO7esZ6IFH1SqJ56t91EbgYMpi6864kJNSITMc+lZRkyFg=
