language: go
install:
- go get -v github.com/spf13/hugo
- sudo pip install --upgrade --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: g468CQpfHFiniFxxsVBhb4TedwP8tqQghGwFLhQy2taI2tf2SPsi2Q0BW7iwrtmvhMaxrirtEg5OTSEWpXFMvHLPGNl/6+a+wUgsoJBua7s+fGAUubWyQze8b4o9BP0B8LUiLmD0pE3htozpWHiFK1HQfVy+HzlNySp64rfUgZqmCyZyM9wai1leGFYlurZk7rYqBMsHjBZxPXtB9EepgTRGJwB5y3ODcRfi7KiYobO+oPdVIVHlWoZkD7LjigZ+/hHEcTar/7Sf1jn9yMNwlBtkUovelL6k6ZaKiATnzHteMZLv9FrRZhIBwUWMOvV19KtkJhq45HZIbdQ2+15s8n6r18t+cap/5DR5srxnrY0p6FrBuQP9Drb6717tlXsSrQmUuzlHMJe4zjkUg2N2XvNsOerjtNn3qrwei9UXpukshdxooxPBgebIsPtOIw4f7fpnYQ3EK9h47iqdUrrHL7dvgkABH0DTvlRoN2q0GBzDAhDJVom5q+BmCgGaF2i84/r2fN68Ce/Qdq9EJYGQ1d8ZNSXArTEs8K2pZIHem36nNH7gBrIMFl/cGGSiW1RxS1I/7/tDJts1VSOgKt+Uve7UO0UWfQYbvrqAaH1421vG2i7u40IIea/UVEqw25LIMz+eQ83gPTLHkTJV6WtCiE+75DQXFYMsXpcZwWSbTDo=
  - secure: kSNxmW7F3OgBB7hhHCFBE+UaPmyJ4GO4Ph5INRR/o72O8/b0e/Mi1AQUIDbFqZSzJV3D9gQHyrzU2SZtSSEhqkOLPBHpeQqtHRReNFCk5UXdMCmvWg0d+Z/tEjcd80p08QjzZbnHNBeS99/XDhiRY2xBYfqvwj6BCzoZVCV9kIuaobeV2dvLqA8HscTtdVYXWNmZWfjHPD2D7kFcClk9uyWfh+d3W+wMuLXGbx0vEFS+UoqnKRDFcf2vP+bbbivPckVHD/2acF+7iv80yBJH8pWfyBsiyxftq8RFtW0HLW81wX0KLP0OUsYpKEzIHFl76yiaStEVpD59pdgM9fd40xlKHDZ0z9gB5eeDlQoAd1PpcUJyZYFLnm50iJ1DiU/QGmWEuIbcJlXSup7OOhZMPTzZ89dKsZHthWNVFO+kGi+BkO2235Oc7CH3/Qtz/MfxFhgL8qIAfdQ+t8tacYxEe5dBQ1RevQXq6HAsruYACudGBwy4/H2K9P+uvAiFqlHQRbBoqiEzNle420xhqMpiycS1KjRhtv4EB1z6F+d2V6MG2m7MROtpqPeSGsqutsoNIU1PniOMnBDomiWsTCCWDz5n+CmQ+r242eHDIrULmZNc/8PQ/AU510AKd0Uvd/Kl8S/X/DXE0TUt6td3uk/2KAS0DeN4qE722Fqsk1OacwE=
