branches:
  only:
  - master
language: go
install:
- go get -v github.com/spf13/hugo
- sudo pip install awscli
script:
- hugo
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: kumasan.space
  skip_cleanup: true
  acl: public_read
notifications:
  email: 
  on_failure: always
env:
  global:
  - secure: hOd1QUfRUGXL3VeD1PREpag6pBcCt/7B8QHiQnmf8fSu+btDAKUwQy9uUjBt7W7dEOMwry99YrVg7eceGnpg0s7a+VEBB+oG053C5Kab+22IkhLkV5E7mZpLxRw3z0CnKFFv4N1Ye2YcZiGB60J8uO3ouUm5IYkc8C+xndATbxeHbu5TLOE7/G22xgk9UAL2trjOSZ4HlEGpgbYX3E3iJ3JsJDfSvY3vbhLzuDsmADD1+d+Ad6o3iPxt9kE3C1N72zZLX2Mn9bPMW1IVGuf2CnfxuZtgh8ng0ekT8RTyM/oo0B7w0V1kTaT76/qRGFoMeRKu3FibzCWTw1B6oHdDZgWUEtRLE5ygTyrBC6PkJiGfToeNR9F0aIb23l8sNWVNnQhcCb41RHstZoWFNm9Mn+TGxU0DgHarrsmIsxu1A33EJYhiXhjKFYVcsKEJ6Jfc9loeKknzjgAwAiYjjFjIo393raQr8+HKZznRgEsXGvn22ELAWg31dcwSgxF73c7Qaxqn/V9Txt52zk3AgSjBuOqo2nd0o/bLnPvP9fDrCosT1p3xDv502x2gfUKJsb0qWOSI/6O0PPslrWV1Len35TcgHf6a6mmYP7CVq68u1G1o7BNardT6MlOqghKgnx6CWEXpidbGWXwvl+df7WZnHAXLh86jvYnHtEY4rjS3fY0=
  - secure: ZwPupD+ZCHBtyDoQp7B9209jZBO2qoUzQGQ8uraWMdTNpa/yth7mXwLzBOn7+A4TI/Fw8hqSkJBvA8xU1G20tSD/3xQPXbwgxSp74shGyMAJ+9iIuWPLa7r3FnbGYRCdznmsJK3Wxl8oXCr8M7qnaXhmC0rdiZNaA/eMflbe6yY+6DPbQ7ZPge4cMYk03DxcZciuLjzyLRgNyKs7gJx8mj3rrQcv+0FqfgxZAwYRapVRJvCCQA8liTmjNopfIoh5bf0uTVjTc1xJQJyRcITlz1Xecx5oJcYpvoKsO1GxzLD7zbnDJuNXw4zjUrpFwlFViBSfrW0kvwHB8H9aEhzdLuTzTNVo8ib4uL+zaZK+iE5AubWsxxVyF7mAVkXsXToIaPJuR3AffW1XmxfUIetvpOdOufUZvJ6mWbvuZi4e2vSjBJWpxMHSPkRI3ZGdwPtON/tME6SlZdO9m6gsaKt+gI/8X/LzlA0JLp5cbUKFSYBh9GZQf4oF2jLuaXOO47FMQ3g6EgcAXsoXx0GHR9yBwtBfxBDbo3Gx9uJKRfHLA4LiWiYtvH4JzP8q1QNAhzsVCD2G+pLYX57dLjOj0FvF8vKOs/GnF+r2GLNr8eNuMjCpCXe6B9mCS5vfVlX5i4zWBt0bkiK673lg8I9+SlbPwyBhtz9aRoOaX8ImtEttUDA=
